linters-settings:
  cyclop:
    max-complexity: 20
  funlen:
    lines: 100
linters:
  enable-all: true
  disable:
    - testpackage
    - exhaustivestruct
    - tagliatelle
    - maligned
    - gomnd